//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventDetail
    {
        public decimal EventId { get; set; }
        public string FoodDetails { get; set; }
        public string StageDetails { get; set; }
        public string LigtingDetails { get; set; }
        public byte[] EventDecorImage { get; set; }
        public string Flowering { get; set; }
        public string SittingPlane { get; set; }
    }
}
