//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocietyInfo
    {
        public string SocietyNmae { get; set; }
        public string PresidentNmae { get; set; }
        public string WisePresident { get; set; }
        public string ContactNumber { get; set; }
        public string ContactNumber1 { get; set; }
        public string FacebookPage { get; set; }
        public string Email { get; set; }
        public int SocietyMamber { get; set; }
        public string SocietyLogo { get; set; }
    }
}
