//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventInfo
    {
        public int EventId { get; set; }
        public string EventName { get; set; }
        public string EventType { get; set; }
        public int Days { get; set; }
        public System.DateTime Date { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string PlaceAddress { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> People { get; set; }
        public string EventStatus { get; set; }
    }
}
