//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonId { get; set; }
        public string PersonName { get; set; }
        public string PersonType { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string SocietyName { get; set; }
        public string Department { get; set; }
        public string PhoneNumber { get; set; }
        public string Password { get; set; }
        public string RegistrationNo { get; set; }
        public string FeedBack { get; set; }
        public object Status { get; internal set; }
    }
}
